import {
  Home,
  Airplay,
  Box,
  FolderPlus,
  Command,
  Cloud,
  FileText,
  Server,
  BarChart,
  Users,
  Layers,
  ShoppingBag,
  List,
  Mail,
  MessageCircle,
  GitPullRequest,
  Monitor,
  Heart,
  Clock,
  Zap,
  CheckSquare,
  Calendar,
  Image,
  Film,
  HelpCircle,
  Radio,
  Map,
  Edit,
  Sunrise,
  Package,
} from 'react-feather';
export const MENUITEMS = [
  {
    menutitle: 'General',
    menucontent: 'Dashboards,Widgets',
    Items: [
      {
        title: 'Dashboard',
        icon: Home,
        type: 'sub',
        badge: 'badge badge-success',
        badgetxt: '2',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/dashboard/default`, title: 'Default', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/dashboard/e-commerce`, title: 'E-commerce', type: 'link' },
        ],
      },
      {
        title: 'Widgets',
        icon: Airplay,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/widgets/general`, title: 'General', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/widgets/chart`, title: 'Chart', type: 'link' },
        ],
      },
    ],
  },

  {
    menutitle: 'Applications',
    menucontent: 'Ready to use Apps',
    Items: [
      {
        title: 'Project',
        icon: Box,
        type: 'sub',
        badge: 'badge badge-danger',
        badgetxt: 'New',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/project/project-list`, type: 'link', title: 'Project-List' },
          { path: `${process.env.PUBLIC_URL}/app/project/new-project`, type: 'link', title: 'New-Project' },
        ],
      },
      {
        title: 'Ecommerce',
        icon: ShoppingBag,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/ecommerce/product`, title: 'Product', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/ecommerce/product-page/1`, title: 'Product-Page', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/ecommerce/product-list`, title: 'Product-List', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/ecommerce/payment-details`, title: 'Payment-Details', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/ecommerce/orderhistory`, title: 'OrderHistory', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/ecommerce/pricing`, title: 'Pricing', type: 'link' },
        ],
      },
      {
        title: 'Users',
        icon: Users,
        path: `${process.env.PUBLIC_URL}/app/users/profile`,
        type: 'sub',
        bookmark: true,
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/users/profile`, type: 'link', title: 'Profile' },
          { path: `${process.env.PUBLIC_URL}/app/users/edit`, type: 'link', title: 'Edit' },
          { path: `${process.env.PUBLIC_URL}/app/users/cards`, type: 'link', title: 'Cards' },
        ],
      },
      { path: `${process.env.PUBLIC_URL}/app/calendar/basic-calendar`, icon: Calendar, title: 'Calendar', type: 'link' },
      { path: `${process.env.PUBLIC_URL}/app/chat-app`, icon: MessageCircle, title: 'Chat-app', type: 'link' },
      { path: `${process.env.PUBLIC_URL}/app/email-app`, icon: Mail, title: 'Email-app', type: 'link' },
      { path: `${process.env.PUBLIC_URL}/app/file-manager`, icon: GitPullRequest, title: 'File-Manager', type: 'link' },
      { path: `${process.env.PUBLIC_URL}/app/kanban-board`, icon: Monitor, badge: 'badge badge-info', badgetxt: 'latest', title: 'Kanban-Board', type: 'link' },
      { path: `${process.env.PUBLIC_URL}/app/bookmark`, icon: Heart, type: 'link', title: 'Bookmark' },
      { path: `${process.env.PUBLIC_URL}/app/task`, icon: CheckSquare, type: 'link', title: 'Task' },
      { path: `${process.env.PUBLIC_URL}/app/social-app`, icon: Zap, type: 'link', title: 'Social-App', bookmark: true },
      { path: `${process.env.PUBLIC_URL}/app/contact`, icon: List, type: 'link', title: 'Contact' },
      { path: `${process.env.PUBLIC_URL}/app/todo-app/to-do`, icon: Clock, type: 'link', title: 'To-do' },
      { path: `${process.env.PUBLIC_URL}/app/todo-app/firebase`, icon: Clock, type: 'link', title: 'Firebase' },
    ],
  },

  {
    menutitle: 'Components',
    menucontent: 'UI Components & Elements',
    Items: [
      {
        title: 'Ui-Kits',
        icon: Box,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/ui-kits/statecolor`, title: 'Statecolor', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/typography`, title: 'Typography', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/avatar`, title: 'Avatar', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/helperclass`, title: 'HelperClass', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/grid`, title: 'Grid', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/tagsandpills`, title: 'TagsandPills', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/progress-bar`, title: 'Progress-bar', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/modal`, title: 'Modal', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/alert`, title: 'Alert', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/popover`, title: 'Popover', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/tooltips`, title: 'Tooltips', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/spinner`, title: 'Spinner', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/dropdown`, title: 'Dropdown', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/accordion`, title: 'Accordion', type: 'link' },
          {
            title: 'Tabs',
            type: 'sub',
            children: [
              { title: 'Bootstrap', type: 'link', path: `${process.env.PUBLIC_URL}/ui-kits/tabs/bootstrap` },
              { title: 'Line', type: 'link', path: `${process.env.PUBLIC_URL}/ui-kits/tabs/line` },
            ],
          },
          { path: `${process.env.PUBLIC_URL}/ui-kits/shadow`, title: 'Shadow', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/ui-kits/list`, title: 'List', type: 'link' },
        ],
      },

      {
        title: 'Bonus-Ui',
        icon: FolderPlus,
        type: 'sub',
        badge1: true,
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/bonus-ui/scrollable`, title: 'Scrollable', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/bootstrap-notify`, title: 'Bootstrap-Notify', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/rating`, title: 'Rating', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/dropzone`, title: 'Dropzone', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/tour`, title: 'Tour', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/sweetalert`, title: 'SweetAlert', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/carousel`, title: 'Carousel', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/ribbons`, title: 'Ribbons', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/pagination`, title: 'Pagination', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/breadcrumb`, title: 'Breadcrumb', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/rangeslider`, title: 'Rangeslider', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/imagecropper`, title: 'ImageCropper', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/sticky`, title: 'Sticky', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/dragdrop`, title: 'DragDrop', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/image-upload`, title: 'Image-Upload', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/card/basic`, title: 'Basic', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/card/creative`, title: 'Creative', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/card/tabbed`, title: 'Tabbed', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/card/draggingcards`, title: 'DraggableCard', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/bonus-ui/timelines/timeline1`, title: 'Timeline1', type: 'link' },
        ],
      },

      {
        title: 'Icons',
        icon: Command,
        path: `${process.env.PUBLIC_URL}/icons/flag_icons`,
        type: 'sub',
        active: false,
        bookmark: true,
        children: [
          { path: `${process.env.PUBLIC_URL}/icons/flag_icons`, title: 'Flag_Icon', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/icons/fontawesome_icon`, title: 'Fontawesome_Icon', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/icons/ico_icon`, title: 'Ico_Icon', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/icons/themify_icons`, title: 'Themify_Icon', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/icons/feather_icons`, title: 'Feather_Icon', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/icons/weather_icons`, title: 'Weather_Icons', type: 'link' },
        ],
      },

      {
        title: 'Buttons',
        icon: Cloud,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/buttons/simplebutton`, title: 'SimpleButton', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/buttons/flat`, title: 'Flat', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/buttons/edge`, title: 'Edge', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/buttons/raised`, title: 'Raised', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/buttons/group`, title: 'Group', type: 'link' },
        ],
      },

      {
        title: 'Charts',
        icon: BarChart,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/charts/apex`, type: 'link', title: 'Apex' },
          { path: `${process.env.PUBLIC_URL}/charts/google`, type: 'link', title: 'Google' },
          { path: `${process.env.PUBLIC_URL}/charts/knob`, type: 'link', title: 'Knob' },
          { path: `${process.env.PUBLIC_URL}/charts/chartjs`, type: 'link', title: 'Chartjs' },
          { path: `${process.env.PUBLIC_URL}/charts/chartist`, type: 'link', title: 'Chartist' },
        ],
      },
    ],
  },

  {
    menutitle: 'Forms & Table',
    menucontent: 'Ready to use froms & tables',
    Items: [
      {
        title: 'Forms',
        icon: FileText,
        type: 'sub',
        menutitle: 'Forms & Table',
        menucontent: 'Ready to use froms & tables',
        active: false,
        children: [
          {
            title: 'Controls',
            type: 'sub',
            children: [
              { title: 'Validation', type: 'link', path: `${process.env.PUBLIC_URL}/forms/controls/validation` },
              { title: 'Input', type: 'link', path: `${process.env.PUBLIC_URL}/forms/controls/input` },
              { title: 'Radio-Checkbox', type: 'link', path: `${process.env.PUBLIC_URL}/forms/controls/radio-checkbox` },
              { title: 'Group', type: 'link', path: `${process.env.PUBLIC_URL}/forms/controls/group` },
              { title: 'MegaOption', type: 'link', path: `${process.env.PUBLIC_URL}/forms/controls/megaoption` },
            ],
          },
          {
            title: 'Widget',
            type: 'sub',
            children: [
              { title: 'Datepicker', type: 'link', path: `${process.env.PUBLIC_URL}/forms/widget/datepicker` },
              { title: 'Timepicker', type: 'link', path: `${process.env.PUBLIC_URL}/forms/widget/timepicker` },
              { title: 'Typeahead', type: 'link', path: `${process.env.PUBLIC_URL}/forms/widget/typeahead` },
            ],
          },
          {
            title: 'Layout',
            type: 'sub',
            children: [
              { path: `${process.env.PUBLIC_URL}/forms/layout/formdefault`, title: 'FormDefault', type: 'link' },
              { path: `${process.env.PUBLIC_URL}/forms/layout/formwizard`, title: 'FormWizard', type: 'link' },
            ],
          },
        ],
      },

      {
        title: 'Table',
        icon: Server,
        type: 'sub',
        children: [
          {
            title: 'ReactstrapTable',
            type: 'sub',
            children: [
              { title: 'BasicTable', type: 'link', path: `${process.env.PUBLIC_URL}/table/reactstraptable/basictable` },
              { title: 'Sizing', type: 'link', path: `${process.env.PUBLIC_URL}/table/reactstraptable/sizing` },
              { title: 'Border', type: 'link', path: `${process.env.PUBLIC_URL}/table/reactstraptable/border` },
              { title: 'Styling', type: 'link', path: `${process.env.PUBLIC_URL}/table/reactstraptable/styling` },
            ],
          },
          {
            title: 'DataTable',
            path: `${process.env.PUBLIC_URL}/table/datatable`,
            type: 'link',
          },
        ],
      },
    ],
  },

  {
    menutitle: 'Pages',
    menucontent: 'All neccesory pages added',
    Items: [
      {
        title: 'Pages',
        icon: Layers,
        type: 'sub',
        badge2: true,
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/pages/samplepage`, title: 'SamplePage', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/pages/searchpage`, title: 'SearchPage', type: 'link' },
        ],
      },
    ],
  },

  {
    menutitle: 'Miscellaneous',
    menucontent: 'Bouns Pages & Apps',
    Items: [
      {
        title: 'Gallery',
        icon: Image,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/gallery/grids`, title: 'Grids', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/gallery/griddesc`, title: 'GridDesc', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/gallery/masonrys`, title: 'Masonrys', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/gallery/masonrydesc`, title: 'MasonryDesc', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/gallery/hover_effect`, title: 'Hover_Effect', type: 'link' },
        ],
      },

      {
        title: 'Blog',
        icon: Film,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/blog/blogdetails`, title: 'BlogDetails', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/blog/blogsingle`, title: 'BlogSingle', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/blog/blogpost`, title: 'BlogPost', type: 'link' },
        ],
      },
      {
        title: 'JobSearch',
        icon: Package,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/jobsearch/cardview`, title: 'CardView', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/jobsearch/joblist`, title: 'JobList', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/jobsearch/jobdetail`, title: 'JobDetail', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/jobsearch/jobapply`, title: 'JobApply', type: 'link' },
        ],
      },
      {
        title: 'Learning',
        icon: Radio,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/learning/learninglist`, title: 'LearningList', type: 'link' },
          { path: `${process.env.PUBLIC_URL}/app/learning/learningdetail`, title: 'LearningDetail', type: 'link' },
        ],
      },
      {
        title: 'Map',
        icon: Map,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/map/googlemap`, type: 'link', title: 'GoogleMap' },
          { path: `${process.env.PUBLIC_URL}/app/map/leafletmap`, type: 'link', title: 'LeafletMap' },
        ],
      },
      {
        title: 'Editor',
        icon: Edit,
        type: 'sub',
        active: false,
        children: [
          { path: `${process.env.PUBLIC_URL}/app/editor/ckeditor`, type: 'link', title: 'CKEditor' },
          { path: `${process.env.PUBLIC_URL}/app/editor/mdeeditor`, type: 'link', title: 'MDEEditor' },
        ],
      },

      { path: `${process.env.PUBLIC_URL}/app/faq`, icon: HelpCircle, type: 'link', active: false, title: 'FAQ' },
      { path: `${process.env.PUBLIC_URL}/app/knowledgebase`, icon: Sunrise, type: 'link', active: false, title: 'Knowledgebase' },
      { path: `${process.env.PUBLIC_URL}/app/support-ticket`, icon: Users, type: 'link', active: false, title: 'Support-Ticket' },
    ],
  },
];
